env:
  global:
    - secure: bbcOE1UV283Uh2BkLkxru3Ua4jWTggjYyKt1nle57Jb7Edxlh8taYQUZ2Et51RIQVNwGwQaEEF0OldSTX5AW91q3b9HtCEu+G5tJRKGU1lBIMP0JNX1bNCTanZjhcMF23SfhlIcZvYAENLInS0zYGbyTbqGR1NKdybmN/2uQ3sL63xYtjf2lFsSLjf5rae2m8RqVk0g4s6Y/BrHvyVmtYVL7BMDO9Bq39E5nmqU6jM0NiNSbcTlhbV+p33EikV5SMdhYvTA3q8zH2MkRYDpiXqXKKyrKg3MWgro/WdZ1b2DdqeSjKsUAr7kqLzZwtWYjr4XDP8eWiBE7yDcf/3In6HSOIprwYXxU0dRE1fiZ5LFvBgTNTT/o+UV1R6UlIwmSopvmjktZhbp2Y57YJUUQQBLL4gAXEXs1OVjS1gHEeAhglTlFcCyszkUBbllkPgFdCuV1nNWMRk627HtJcdwhUzUOIU9CIt8rxHhhWiZtFnM5sYaO3zdhAoONL+kfuA4ONWHbYmnOckuUpCW6hNCix0iBVreWoorSZc4eXEyNLNKvuXgeFxCRhoxnbdEiw/nY6Nx9VgRsn/qJoh67JykI/eNWYuRs75ZYrPUmo+1kiN6zcvz5eROvIcFdNc9KqlO6GHp9hzAXN/GWOLW/h1KhCpe3cqnTgvdcSDv0o+exs5A=
    - secure: R2eZjYEllKkqPLdyiMr9Bii8DCMnlDQenjANQtG/oC43eD518dTEnxGPHdmI0sHSIfYb4hVkSFZ5iw0A0nNJXPLX9rjdQgFAtzt/FT3wKuj6n8VGXawz+s5RT6UPA+ht4g70sl/HgmjPDtrZKVIsDD1T2Me8ENUGN8qHtw5xeXTlUhU0nzSEp9TyYCtpwpp6zlfREHhsPvEWTvLSmnUIQ+O1f1HrSvDbFUaaetxJpF7Hit9d4+DoDztzFVOOK8FSQGLCH1JbMw20KteNsCiGJr7vOPNZacnLdd1eRKyhmIZXbAOjTPcysn5KiHJFIt4uS/RkVcpCU657tP+NCuD21mBmGd8o1X3QjwWfTSsrWuX6Z8RXNwbuRGQDBdDez+3G+pUjyroIktDSrFpjf9SHHe+Fy74MYqHYaD2GVYCHQC3t1Cw0GLSUtJLUrXk2qw8hQwiorvL3hXdv3+z9fx3H5vM3hIYFUqWGO0KBJsl7/m6HF70bDNNKrNzTpXkd0xEdU76l0QjgcbybzDaplAjH3ENsmVZK+oOL1kFB54Xfwc5GGrP/c0cEJ1DtO5TQcKFR1BdeER/Ekn6CBkCjambp4Arx4khnUsYRrTjQ3YozuEKnhoDdMKqyfN36UDB7ywBFI6DwC1JHheEMlULR4SXhMurOxrTCWLKsCawBMCBBfco=
addons:
  sauce_connect: true
language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g nightwatch
script:
  - nightwatch -c tests/nightwatch.json -e saucelabs -t tests/maps.js

